inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.0
  TargetRailsVersion: 7.0.1
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

Rails:
  Enabled: true

Rails/FilePath:
  Exclude:
    - 'spec/rails_helper.rb'

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  CountComments: false
  Exclude:
    - 'Guardfile'
    - 'config/routes.rb'
    - 'spec/**/*'
    - 'app/views/**/*.jbuilder'

Naming/FileName:
  Exclude:
    - 'Gemfile'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
